config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost:3000/'
  devise_for :managers
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :managers do
    resources :products
    resources :orders
    resources :profiles, only: :show
  end
  namespace :users do
    resources :products, only: %i[index show]
    resources :cart_products, only: %i[index new destroy]
    resource :cart, only: :destroy
    resources :orders, only: %i[new show create index]
    resources :profiles, only: :show
    root 'products#index'
  end
  authenticated :manager do
    root 'managers/products#index', as: :manager_root
  end

  authenticated :user do
    root 'users/products#index', as: :user_root
  end
  root 'users/products#index'
end

app/models/manager.rb
class Manager < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, dependent: :destroy
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :amount, :price, :description, presence: true
  belongs_to :manager

  has_many :ordered_products
  has_many :orders, through: :ordered_products, dependent: :destroy

  has_attached_file :avatar,
                    styles: { medium: '266x200>', large: '532x400>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/managers/orders_controller.rb
class Managers::OrdersController < ApplicationController
  before_action :authenticate_manager!

  # expose_decorated :ordered_products, -> { OrderProduct.all }
  # expose_decorated :ordered_product

  expose_decorated :orders, -> { Order.all }

  def index; end

  def show; end

  def edit; end

  def update
    @order = Order.update(order_params)
    @order.save
  end

  def order_params
    params.require(:order).permit(
      :user_id,
      :status,
      ordered_products_attributes: %i[product_id order_id amount _destroy]
    )
  end
end

app/controllers/managers/products_controller.rb
class Managers::ProductsController < ApplicationController
  before_action :authenticate_manager!, except: %i[index show]

  expose_decorated :products, -> { init_products }
  expose_decorated :product

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    product.manager = current_manager
    product.save
    respond_with :managers, product
  end

  def update
    product.update(product_params)
    respond_with :managers, product
  end

  def destroy
    product.destroy
    respond_with :managers, product
  end

  private

  def init_products
    products = Product.all
    products = products.where('name ILIKE ?', "%#{params[:search]}%") if params[:search]
    products.page(params[:page]) # returns
  end

  def product_params
    params.require(:product).permit(
      :name,
      :avatar,
      :amount,
      :price,
      :description
    )
  end
end

app/controllers/managers/profiles_controller.rb
class Managers::ProfilesController < ApplicationController
  before_action :authenticate_manager!
  expose_decorated :profile, -> { set_profile }

  def show; end

  private

  def set_profile
    Manager.find(params[:id])
  end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  expose_decorated :products, -> { init_products }
  expose_decorated :product

  def index; end

  def show; end

  private

  def init_products
    products = Product.where("amount > '0'")
    products = products.where('name ILIKE ?', "%#{params[:search]}%") if params[:search]
    products.page(params[:page]) # returns
  end
end

app/views/managers/products/_form.html.slim
.alert.alert-info
  = simple_form_for [:managers,product] do |f|
    = f.error_notification
    = f.input :name
    p = t('product.avatar')
    = f.input :avatar, as: :file, label:false
    = f.input :description, as: :text
    = f.input :price, as: :numeric
    = f.input :amount, as: :numeric
    = f.button :submit, class: 'btn-success'

app/views/managers/products/_product.html.slim
.card
  .image
    = image_tag product.avatar.url(:medium)
  hr
  .title
    h3 = link_to product.name,[:managers, product]
    p.card-text = product.truncated_description
  .price
    = product.price_in_dollars

app/views/managers/products/edit.html.slim
.container
  .row
    .col
    .col-auto
      h3.title.title-field = t('product.edit.title')
      = render 'form'
      = link_to t('links.back'), :back, class: 'btn btn-outline-link'
    .col

app/views/managers/products/index.html.slim
= render "layouts/jumbotron"
.album.text-muted
  .container
    .row
      = render products
    = paginate products, theme: 'twitter-bootstrap-4'

app/views/managers/products/new.html.slim
.container
  .row
    .col
    .col-auto
      h3.title.title-field  = t('product.new.title')
      = render 'form'
      = link_to t('links.back'), :back, class: 'btn btn-outline-link'
    .col

app/views/managers/products/show.html.slim
.container
  .row.title-field
    .col
    .col-auto
      .card
        .large_image
          = image_tag product.avatar.url(:large)
        .name_of_product
          h3 = link_to product.name,[:managers, product]
        .description_of_product
          = product.description
        .stock
          = product.current_amount
        .price
          = product.price_in_dollars
        - if manager_signed_in?
          = link_to t('links.edit'), edit_managers_product_path(product), class: 'btn btn-outline-info product_button'
          = link_to t('links.destroy'),[:managers, product], method: :delete, data: {confirm: t('links.confirm')}, class: 'btn btn-outline-danger product_button'
        = link_to t('links.back'), :back, class: 'btn btn-outline-secondary product_button'
    .col