config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost:3000/'
  devise_for :managers
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :managers do
    resources :products
    resources :orders
    resources :profiles, only: :show
  end
  namespace :users do
    resources :products, only: %i[index show]
    resources :cart_products, only: %i[index new destroy]
    resource :cart, only: :destroy
    resources :orders, only: %i[new show create index]
    resources :profiles, only: :show
    root 'products#index'
  end
  authenticated :manager do
    root 'managers/products#index', as: :manager_root
  end

  authenticated :user do
    root 'users/products#index', as: :user_root
  end
  root 'users/products#index'
end

app/views/layouts/_flash.html.slim
.container
  .row
    .col
    .col-auto
      - flash.each do |name, msg|
        = content_tag :div, msg, class: name
    .col

app/views/layouts/_footer.html.slim
hr
footer.text-muted
  .container
    p.float-right
      a href="#"  Back to top
    p
      = link_to t('footer.homepage'), root_path
      = t('footer.read_our')
      = link_to 'F.A.Q.', root_path

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a = link_to "E-commerce", root_path, class: 'navbar-brand'
  #navbarSupportedContent.collapse.navbar-collapse
    - if anyone_signed_in?
      - if manager_signed_in?
        = render 'layouts/manager_header'
      - if user_signed_in?
        = render 'layouts/user_header'
    - else
      ul.navbar-nav.mr-auto
      form.form-inline.my-2.my-lg-0
        = form_tag users_products_path, method: :get do
          = text_field_tag :search, params[:search], placeholder:  t('links.search'),
          class: 'form-control mr-sm-2'
          = submit_tag t('links.search'), name: nil,
          class: 'btn btn-outline-success my-2 my-sm-0'
      ul.nav.nav-pills.float-right
        li.nav-item
          = link_to t('devise.sessions.new.sign_in'), new_user_session_path, class: 'nav-link'

app/views/layouts/_jumbotron.slim
main role="main"
  section.jumbotron.text-center
    .container
      h1.jumbotron-heading = t('jumbotron.heading')
      p.lead.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas eget velit id hendrerit. Vestibulum consectetur nunc ornare, blandit massa eget, viverra neque. Etiam in tempor ante. Phasellus velit arcu, scelerisque vitae nisi pellentesque, consequat vehicula magna.
      p
        = link_to t('jumbotron.popular_button'),"#",
          class: 'btn btn-outline-primary alert_button_size'
        = link_to t('jumbotron.about_us'),"#",
          class: 'btn btn-outline-secondary alert_button_size'

app/views/layouts/_manager_header.slim
ul.navbar-nav.mr-auto
  li.nav-item
    a = link_to t('manager_nav.create_product'), new_managers_product_path, class: 'nav-link'
  li.nav-item
    a = link_to t('manager_nav.my_orders'), managers_orders_path, class: 'nav-link'
= render 'layouts/search'
ul.nav.nav-pills.float-right
  li.nav-item.dropdown
    a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
      = current_manager.email
    .dropdown-menu aria-labelledby="navbarDropdown"
      a = link_to t('manager_nav.profile'), managers_profile_path(current_manager), class: 'dropdown-item'
      .dropdown-divider
      a = link_to t('devise.sessions.sign_out'), destroy_manager_session_path,
      method: "delete", class: 'dropdown-item'

app/views/layouts/_search.slim
form.form-inline.my-2.my-lg-0
  = form_tag managers_products_path, method: :get do
    = text_field_tag :search, params[:search], placeholder: t('links.search'), class: 'form-control mr-sm-2'
    = submit_tag t('links.search'), name: nil, class: 'btn btn-outline-success my-2 my-sm-0'

app/views/layouts/_user_header.slim
ul.navbar-nav.mr-auto
  li.nav-item
    = link_to users_cart_products_path, class: 'nav-link' do
      = t('user_nav.my_cart')
      span.badge.badge-info
        = "#{ session[:cart] ? session[:cart].uniq.size : ""}"
  li.nav-item
    a = link_to t('user_nav.my_orders'), users_orders_path, class: 'nav-link'
= render 'layouts/search'
ul.nav.nav-pills.float-right
  li.nav-item.dropdown
    a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
      = current_user.email
    .dropdown-menu aria-labelledby="navbarDropdown"
      a = link_to t('user_nav.profile'), users_profile_path(current_user), class: 'dropdown-item'
      .dropdown-divider
      a = link_to t('devise.sessions.sign_out'), destroy_user_session_path,
      method: "delete", class: 'dropdown-item'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="content">
        <%= render "layouts/header" %>
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
      <div class="footer">
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>